# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
#' @useDynLib antibodyKinetics
predict_titres <- function(params, times) {
    .Call('antibodyKinetics_predict_titres', PACKAGE = 'antibodyKinetics', params, times)
}

#' Converts to unit scale
#'
#' @param x the double to be converted
#' @param min the minimum value on the linear scale
#' @param max the maximum value on the linear scale
#' @return the value converted to a unit scale
#' @export
toUnitScale <- function(x, min, max) {
    .Call('antibodyKinetics_toUnitScale', PACKAGE = 'antibodyKinetics', x, min, max)
}

#' Converts to linear scale
#'
#' @param x the double to be converted back to linear scale
#' @param min the minimum value on the linear scale
#' @param max the maximum value on the linear scale
#' @return the value converted to a linear scale
#' @export
fromUnitScale <- function(x, min, max) {
    .Call('antibodyKinetics_fromUnitScale', PACKAGE = 'antibodyKinetics', x, min, max)
}

#' @export
obs_error <- function(actual, obs, S, EA) {
    .Call('antibodyKinetics_obs_error', PACKAGE = 'antibodyKinetics', actual, obs, S, EA)
}

#' @export
posterior <- function(y, data, params) {
    .Call('antibodyKinetics_posterior', PACKAGE = 'antibodyKinetics', y, data, params)
}

